# Generated by Django 4.2.7 on 2023-12-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_made',
        ),
    ]
