# Generated by Django 4.2.7 on 2023-12-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0002_delete_payment_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_made',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('cash', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.TextField(blank=True, max_length=255, null=True)),
                ('gst_number', models.TextField(blank=True, max_length=255, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_id', models.IntegerField(blank=True, null=True)),
                ('opening_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('total_opening_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('sum_amount_due', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
    ]
