# Generated by Django 4.2.7 on 2023-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_payment_made'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_item',
        ),
    ]
