# Generated by Django 4.2.7 on 2023-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_sales_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_table',
            name='credit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
