# Generated by Django 4.2.7 on 2023-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_alter_vendor_table_opening_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_table',
            name='opening_bal',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
