# Generated by Django 4.2.7 on 2023-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_purchaseorderreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
