# Generated by Django 4.2.7 on 2023-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_purchase_order_cheque_id_purchase_order_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='complete_status',
            field=models.IntegerField(default=0),
        ),
    ]
