# Generated by Django 4.2.7 on 2024-02-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0014_purchase_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item_purchase',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.invoice_purchase'),
        ),
        migrations.AlterField(
            model_name='recur_itemtable_purchase',
            name='ri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.recurring_invoice_purchase'),
        ),
        migrations.CreateModel(
            name='doc_upload_table_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('document', models.FileField(upload_to='doc/')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.purchase_order')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
