# Generated by Django 4.2.7 on 2024-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_alter_invoice_item_purchase_inv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='customer_source_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
