# Generated by Django 4.2.7 on 2024-03-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_purchase_order_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
