# Generated by Django 3.2.20 on 2023-09-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_auto_20230927_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat_every',
            name='num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
