# Generated by Django 3.2.20 on 2023-10-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0023_recurring_invoice_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
