# Generated by Django 3.2.20 on 2023-10-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0028_auto_20231009_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='repeat_every',
        ),
        migrations.AddField(
            model_name='expense',
            name='repeatevery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.repeat_every'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
