# Generated by Django 3.2.20 on 2023-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_auto_20231009_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
