# Generated by Django 3.2.20 on 2023-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0030_alter_expense_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='adjust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='complete_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pay_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
