# Generated by Django 3.2.20 on 2023-10-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0032_auto_20231010_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project1',
            name='end',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project1',
            name='start',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='billdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='projectfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='doc/')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1')),
            ],
        ),
        migrations.CreateModel(
            name='projectcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1')),
            ],
        ),
    ]
