# Generated by Django 3.2.20 on 2023-10-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0037_additem_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='paid_amount',
        ),
    ]
