# Generated by Django 3.2.20 on 2023-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0039_addgodown_attachgodown_comments_godown_delete_godown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='destination',
            new_name='cust_gsttreatment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='ends_on',
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cust_placeofsupply',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='refrenceid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
