# Generated by Django 3.2.20 on 2023-10-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0040_auto_20231026_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='adjust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='complete_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pay_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
