# Generated by Django 3.2.20 on 2023-10-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0041_auto_20231028_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('bank', 'Bank')], max_length=50)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zohoapp.bankcreation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.invoice')),
            ],
        ),
    ]
