# Generated by Django 3.2.20 on 2023-11-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0044_auto_20231101_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_made',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_made',
            name='reference',
            field=models.IntegerField(default=1),
        ),
    ]
