# Generated by Django 3.2.20 on 2023-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0046_payroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
