# Generated by Django 3.2.20 on 2023-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0047_payment_made_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
