# Generated by Django 3.2.20 on 2023-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0048_payment_made_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cust_gstin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
