# Generated by Django 3.2.20 on 2023-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0049_expense_cust_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salaryrange',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-15', '10-15'), ('15-31', '15-31')], default='1-10', max_length=10),
        ),
    ]
