# Generated by Django 3.2.20 on 2023-11-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0050_auto_20231110_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_made',
            old_name='amount',
            new_name='bill_id',
        ),
        migrations.AddField(
            model_name='payment_made',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
