# Generated by Django 3.2.20 on 2023-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0051_auto_20231120_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
