# Generated by Django 3.2.20 on 2023-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0053_cust_comment_recur_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='opening_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_made',
            name='reference',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
