# Generated by Django 3.2.20 on 2023-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0055_alter_payment_made_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='total_opening_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
