# Generated by Django 3.2.20 on 2023-11-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0056_payment_made_total_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='sum_amount_due',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
