# Generated by Django 3.2.20 on 2023-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0057_payment_made_sum_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retaineritems',
            name='itemname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retaineritems',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retaineritems',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
