# Generated by Django 4.2.7 on 2023-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0058_auto_20231201_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='adjustment_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='convert_status',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='payed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
